Allow developers to specify the configuration programmatically.
unitsofmeasurement/unit-tck pull request #43
Opened 2022-07-19 17:12 UTC by desruisseaux

Same as https://github.com/unitsofmeasurement/unit-tck/pull/32

2022-07-19 17:54 UTC, keilw requested changes
Even if it has no effect on the default behavior, could the programmatic configuration be documented?

2022-07-20 09:10 UTC, desruisseaux commented
Done. I also modified the proposal with an `initialize(…)` method instead of `setConfiguration(…)`. The intent is to make sure that the configuration can not be changed after the tests started.

2022-07-20 16:58 UTC, keilw commented
How does this look for testers/implementers if they want to customize the TCK run?
There are two places:
- https://github.com/unitsofmeasurement/unit-tck/blob/master/README.md
- https://unitsofmeasurement.github.io/unit-tck/
Where any adjustment or argument should be documented in both of them.
If you want we could create a separate issue/PR for the documentation, but a new 2.1.2 release of the TCK may only be published, once those are documented. 

If required we may also have to revisit or update https://github.com/unitsofmeasurement/unit-tck-usage

2022-07-20 17:35 UTC, desruisseaux commented
I think it does not change anything to those documentation. In particular, this commit does not add any new parameter to supply on the command line. It rather provides an alternative way to run the TCK. Instead of the following steps documented in `README.md`:

> 1. Create a new Maven project.
> 2. Add this TCK and your implementation as dependency.
> 3. Implement a class of type `tech.units.tck.TestSetup`,

We would have (note that there is no "create new Maven project step"):

1. Add this TCK as a dependency in your project with `<scope>test</scope>`.
2. Add a test class implementing `tech.units.tck.util.ServiceConfiguration`.
3. Add a test method like below:

```java
import tech.units.tck.TCKSetup;
import tech.units.tck.TCKRunner;

public class MyTest implements ServiceConfiguration
    @Test
    public void runTCK() {
        TCKSetup.initialize(this);
        final TCKRunner runner = new TCKRunner();
        int returnCode = runner.run(null, null, null);
        assertEquals("Some TCK tests failed.", 0, returnCode);        
    }
}
```

With that, the TCK is part of project test suite and is run every time that the project is build. It does not require that we create and run a separated project.

So it is not a change in current instruction. It would be a separated section for another way to run the TCK.

2022-08-25 19:28 UTC, keilw commented
There is no "Create new Maven project" step, but we would have to somehow document it if not here then in the "blueprint" project https://github.com/unitsofmeasurement/unit-tck-usage.

2023-02-03 11:32 UTC, desruisseaux commented
Did the following changes in the `README.md` file:

* [Added documentation about this way to run the tests](https://github.com/Geomatys/unit-tck#integrate-with-implementation-tests)
* [Added a "Test in a separated Maven project" header to previous documentation](https://github.com/Geomatys/unit-tck#unit-tck)

However I do not know how to edit the https://unitsofmeasurement.github.io/unit-tck/ page.

2023-02-03 18:38 UTC, keilw commented
You can make changes in the [docs](https://github.com/unitsofmeasurement/unit-tck/tree/master/docs) folder of this repo, mostly index.html, the rest should rarely change, unless you add further images.

2023-02-25 13:28 UTC, desruisseaux commented
I propose to withdrawn this merge request. A few months ago I could get it working with Seshat, but it is no longer the case. TestNG and JUnit have numerous conflicts in their dependencies, so I abandon the attempt to integrate TCK tests in Seshat test suite. Instead I created a separated Maven project for running the TCK, which is what the current instructions propose to do.

Note that I still can't get the TCK to run, but this is a separated issue than this pull request.

2023-02-25 13:28 UTC, closed without merging

2023-02-27 14:26 UTC, keilw commented
Ok, then is the whole `initialize()` approach something we should no longer consider for MR2?
Note I did have to change some test methods in the TCK after upgrading to the latest version of Reflections.io but it works now also in https://github.com/unitsofmeasurement/unit-tck-usage/. About the Maven project, what's wrong with https://github.com/unitsofmeasurement/unit-tck-usage/tree/seshat ? I know it is old, probably still at Seshat 1.0 but wouldn't it be possible to upgrade dependencies in that branch and run it there?

2023-02-27 16:53 UTC, keilw commented
Mixing JUnit and TestNG is not really recommended, we use JUnit 5 everywhere for module tests in the RI (Indriya) while TestNG is used for the TCK, and that likely won't change anytime soon (the main reason for the TCK was easier configuration even at runtime by passing XML definitions, JUnit may have equivalents but v4 did not have much then)

Regarding a module-info, there is a ticket #47 for that already. As no Multi-Release JAR is required, a compile-cycle similar to [JSR 354](https://github.com/JavaMoney/jsr354-api/blob/master/pom.xml) or [Jakarta JSON Processing (2.0.x) ](https://github.com/jakartaee/jsonp-api/blob/2.0.2/api/pom.xml) instead of the Toolchain or AntRun plugins used here in most repositories.